export const WeatherStatusIcons: {[key: number]: string | string[]} = {
    0: ['day.svg', 'night.svg'],
    1: ['cloudy-day-1.svg', 'cloudy-night-1.svg'],
    2: ['cloudy-day-3.svg', 'cloudy-night-1.svg'],
    3: 'cloudy.svg',
    45: 'cloudy.svg',
    48: 'cloudy.svg',
    51: 'cloudy.svg',
    53: 'cloudy.svg',
    55: 'cloudy.svg',
    56: 'cloudy.svg',
    57: 'cloudy.svg',
    61: 'rainy-3.svg',
    63: 'rainy-5.svg',
    65: 'rainy-7.svg',
    66: 'rainy-4.svg',
    67: 'rainy-7.svg',
    71: 'snowy-4.svg',
    73: 'snowy-5.svg',
    75: 'snowy-6.svg',
    77: 'snowy-6.svg',
    80: 'rainy-4.svg',
    81: 'rainy-5.svg',
    82: 'rainy-7.svg',
    85: 'snowy-4.svg',
    86: 'snowy-6.svg',
    95: 'thunder.svg',
    96: 'thunder.svg',
    99: 'thunder.svg',
}